### ISSUE TITLE
npm dependency issue.

### ISSUE THREAD

**Issue by jaideepghosh** [coreui/coreui-free-vue-admin-template#134]
Hi,
I'm trying to start with CoreUI free admin panel but getting the following error after executing `npm install`

```
Binary is fine
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @coreui/coreui@2.0.20 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.1.3 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN babel-loader@8.0.4 requires a peer of @babel/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @coreui/coreui-free-vue-admin-template@2.0.2 No repository field.

added 1945 packages from 1183 contributors and audited 33726 packages in 32.949s
found 6 vulnerabilities (1 low, 4 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

After installation, I tried to start the app using: `npm start` but the output is:

```
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jaideep/.npm/_logs/2018-10-21T08_24_28_420Z-debug.log
```

Contents of the 2018-10-21T08_24_28_420Z-debug.log file is:

```

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose stack Error: missing script: dev
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:418:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:373:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:416:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:364:12
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
5 verbose cwd /Users/jaideep/Documents/CoreUI/free
6 verbose Darwin 17.7.0
7 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
8 verbose node v8.12.0
9 verbose npm  v6.4.1
10 error missing script: dev
11 verbose exit [ 1, true ]

```

So please help me to fix this issue ASAP.

**Comment by xidedix** [comment]
hi @jaideepghosh 
Please read usage section of README.md
https://github.com/coreui/coreui-free-vue-admin-template/blob/master/README.md#usage

it states `npm run serve`
