### ISSUE TITLE
 Failed at the chromedriver@2.46.0 install script

### ISSUE THREAD

**Issue by rasool1994** [coreui/coreui-free-vue-admin-template#168]
on ubuntu 18.04,
when i try npm install, i get following error:
```

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chromedriver@2.46.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chromedriver@2.46.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rasool/.npm/_logs/2019-09-14T06_45_48_238Z-debug.log : 
```

and end of detailed log file:
```

1042 warn @coreui/coreui@2.1.12 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
1043 warn bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
1044 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
1045 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
1046 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
1046 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
1046 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
1046 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
1047 verbose stack Error: chromedriver@2.46.0 install: `node install.js`
1047 verbose stack Exit status 1
1047 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
1047 verbose stack     at EventEmitter.emit (events.js:198:13)
1047 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
1047 verbose stack     at ChildProcess.emit (events.js:198:13)
1047 verbose stack     at maybeClose (internal/child_process.js:982:16)
1047 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
1048 verbose pkgid chromedriver@2.46.0
1049 verbose cwd /home/rasool/workspace/CoreUI-Vue
1050 verbose Linux 4.15.0-62-generic
1051 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
1052 verbose node v10.16.3
1053 verbose npm  v6.9.0
1054 error code ELIFECYCLE
1055 error errno 1
1056 error chromedriver@2.46.0 install: `node install.js`
1056 error Exit status 1
1057 error Failed at the chromedriver@2.46.0 install script.
1057 error This is probably not a problem with npm. There is likely additional logging output above.
1058 verbose exit [ 1, true ]

```

**Comment by woothu** [comment]
Hi! Thank you for reporting this issue!

Please try install chromedriver by command 

> npm install chromedriver --chromedriver_cdnurl=https://npm.taobao.org/mirrors/chromedriver

If it doesn't work out you can also try another method from
https://www.npmjs.com/package/chromedriver

After installation of chromedriver try to run npm install

**Comment by vucat12** [comment]
Install chromedriver with npm on a Mac with an M1 processor and getting "Only Mac 64 bits supported."
Using command
> npm install chromedriver@87.0.1
