### ISSUE TITLE
Error loading vue.config.js:

### ISSUE THREAD

**Issue by unitedmp** [coreui/coreui-free-vue-admin-template#275]
ERROR  Error loading vue.config.js:
 ERROR  TypeError: defineConfig is not a function
TypeError: defineConfig is not a function
    at Object.<anonymous> (E:\Projects\Others\CoreUI-Vue\vue.config.js:2:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Service.loadUserOptions (E:\Projects\Others\CoreUI-Vue\node_modules\@vue\cli-service\lib\Service.js:283:22)
    at Service.init (E:\Projects\Others\CoreUI-Vue\node_modules\@vue\cli-service\lib\Service.js:72:30)
    at Service.run (E:\Projects\Others\CoreUI-Vue\node_modules\@vue\cli-service\lib\Service.js:204:10)

**Comment by iamchikalov** [comment]
I have the same error, can't fix it

**Comment by xduduaraujo** [comment]
Just change your version of @vue/cli-service to latest version:

![image](https://user-images.githubusercontent.com/66920988/169070121-da268f6b-94a6-47ea-bbb3-9fbf2ce5e735.png)

then run:
`yarn install`

Should work

**Comment by Ahmed-Trabelsi0** [comment]
> vue --version 
@vue/cli 5.0.8
"@vue/cli-service": "5.0.8",

Works for me thanks !!

**Comment by EnzoSives** [comment]
Me sirvio! Muchas gracias!

**Comment by nerfereyes** [comment]
This worked for me. Thank you! :)

**Comment by M-Deniz** [comment]
> Just change your version of @vue/cli-service to latest version:
> 
> ![image](https://user-images.githubusercontent.com/66920988/169070121-da268f6b-94a6-47ea-bbb3-9fbf2ce5e735.png)
> 
> then run: `yarn install`
> 
> Should work

Worked for me without any hassle, i just had to use `npm install`. 
Thank you. 👍

**Comment by Theandev** [comment]
![image](https://github.com/coreui/coreui-free-vue-admin-template/assets/149214718/68a29ea1-a895-40d6-a2a5-89a211289895)

**Comment by Theandev** [comment]
I'm not working
