### ISSUE TITLE
Issue running in MAMP.

### ISSUE THREAD

**Issue by hifall** [coreui/coreui-free-vue-admin-template#77]
I am trying to run this project on macOS 10.12/MAMP 4.4.1, and I am running into the following issue.

When I tried: npm run dev, it failed with the following messages:

> @coreui/vue@1.0.12 dev /Applications/MAMP/htdocs
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

/Applications/MAMP/htdocs/build/webpack.base.conf.js:43
      ...(config.dev.useEslint ? [createLintingRule()] : []),
      ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Applications/MAMP/htdocs/build/webpack.dev.conf.js:7:27)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v4.2.6
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! @coreui/vue@1.0.12 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @coreui/vue@1.0.12 dev script 'webpack-dev-server --inline --progress --config build/webpack.dev.conf.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @coreui/vue package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --inline --progress --config build/webpack.dev.conf.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @coreui/vue
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @coreui/vue
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Applications/MAMP/htdocs/npm-debug.log

Any idea on how to get around this?

Thanks!

**Comment by xidedix** [comment]
Hi @hifall 

You have installed `node v4.2.6` and `npm v3.6.0`.
Please try update to `node v8.x` and let us know if it helps.

See also: [Node 4.x is End Of Life](https://medium.com/the-node-js-collection/april-2018-release-updates-from-the-node-js-project-71687e1f7742)

**Comment by hifall** [comment]
After upgrading to node 8.11.1, and running npm run dev, I got:

> @coreui/vue@1.0.12 dev /Applications/MAMP/htdocs
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 94% asset optimization                                                       n      
 ERROR  Failed to compile with 1 errors                                 19:34:24

Module build failed: Error: No ESLint configuration found.
    at Config.getLocalConfigHierarchy (/Applications/MAMP/htdocs/node_modules/eslint/lib/config.js:255:39)
    at Config.getConfigHierarchy (/Applications/MAMP/htdocs/node_modules/eslint/lib/config.js:179:43)
    at Config.getConfigVector (/Applications/MAMP/htdocs/node_modules/eslint/lib/config.js:286:21)
    at Config.getConfig (/Applications/MAMP/htdocs/node_modules/eslint/lib/config.js:329:29)
    at processText (/Applications/MAMP/htdocs/node_modules/eslint/lib/cli-engine.js:163:33)
    at CLIEngine.executeOnText (/Applications/MAMP/htdocs/node_modules/eslint/lib/cli-engine.js:620:17)
    at lint (/Applications/MAMP/htdocs/node_modules/eslint-loader/index.js:229:17)
    at Object.module.exports (/Applications/MAMP/htdocs/node_modules/eslint-loader/index.js:224:21)

**Comment by xidedix** [comment]
- run `npm install` in the root directory of your app, ex:
````bash
cd Vue_Full_Project
npm install
````
- also possible that [ESLint](https://eslint.org/docs/user-guide/getting-started) need configuration on your machine
````bash 
./node_modules/.bin/eslint --init
````
- or you can turn off linting for a while in `./config/index.js` file - set:
````js
useEslint: false,
````
